simuladosaep/Models/Professor.cs
using System;
using System.Collections.Generic;

namespace simuladosaep.Models;

public partial class Professor
{
    public int ProfessorId { get; set; }

    public string? Nome { get; set; }

    public string? Email { get; set; }

    public string? Senha { get; set; }

    public virtual ICollection<Turma> Turmas { get; set; } = new List<Turma>();
}

simuladosaep/Controllers/ProfessorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using simuladosaep.Contexts;
using simuladosaep.Models;

namespace simuladosaep.Controllers
{
    public class ProfessorsController : Controller
    {
        private readonly DbDevContext _context;

        public ProfessorsController(DbDevContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var professorId = HttpContext.Session.GetInt32("ProfessorId");

            if (professorId == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var professor = _context.Professors.Find(professorId);

            var turmas = _context.Turmas.Where(x => x.ProfessorId == professorId).ToList();

            ViewBag.NomeProfessor = professor.Nome;
            return View(turmas);
        }

        [HttpPost]
        public IActionResult CadastrarTurma(string nomeTurma)
        {
            int? professorId = HttpContext.Session.GetInt32("ProfessorId");

            var turma = new Turma()
            {
                Nome = nomeTurma,
                ProfessorId = professorId,

            };

            _context.Turmas.Add(turma);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public IActionResult DeletarTurma(int idTurma)
        {
            var turma = _context.Turmas.Find(idTurma);

            if (turma == null)
            {
                return NotFound();
            }

            var hasActivities = turma.Atividades.Any();

            if (hasActivities)
            {
                _context.Atividades.RemoveRange(turma.Atividades);
            }

            _context.Remove(turma);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Professors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professors
                .FirstOrDefaultAsync(m => m.ProfessorId == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        // GET: Professors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Professors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProfessorId,Nome,Email,Senha")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(professor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        // GET: Professors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professors.FindAsync(id);
            if (professor == null)
            {
                return NotFound();
            }
            return View(professor);
        }

        // POST: Professors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProfessorId,Nome,Email,Senha")] Professor professor)
        {
            if (id != professor.ProfessorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(professor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessorExists(professor.ProfessorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        // GET: Professors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professors
                .FirstOrDefaultAsync(m => m.ProfessorId == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        // POST: Professors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var professor = await _context.Professors.FindAsync(id);
            if (professor != null)
            {
                _context.Professors.Remove(professor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfessorExists(int id)
        {
            return _context.Professors.Any(e => e.ProfessorId == id);
        }
    }
}

simuladosaep/Views/Professors/Index.cshtml
@{
    ViewData["Title"] = ViewBag.NomeProfessor;
}

<div style="display:flex">
    <h3>@ViewBag.NomeProfessor</h3>

    <form asp-controller="Login" asp-action="Logout" method="post">
        <button type="submit">Sair</button>
    </form>

    
</div>

<form asp-controller="Professors" asp-action="CadastrarTurma" method="post">
    <input type="text" name="nomeTurma" placeholder="Nome da Turma" />
    <button type="submit">Cadastrar</button>
</form>

<h1>Sua lista de turmas</h1>

<div>
    <table>
        <thead>
            <tr>
                <th>
                    Numero
                </th>
                <th>
                    Nome da Turma
                </th>
                <th>
                    Ações
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var turma in Model)
            {
                <tr>
                    <td>@turma.TurmaId</td>
                    <td>@turma.Nome</td>
                    <td>
                        <form asp-action="DeletarTurma" method="delete">
                            <input type="hidden" name="turmaId" value="@turma.TurmaId"/>
                            <button type="submit">Excluir</button>
                        </form>
                        <form asp-action="EditarTurma" method="dialog">
                            <input type="hidden" name="turmaId" value="@turma.TurmaId" />
                            <button type="submit">Editar</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>